//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=ShopOnline;Persist Security Info=True;User " +
            "ID=sa;Password=291284")]
        public string ShopOnlineConnectionString {
            get {
                return ((string)(this["ShopOnlineConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CUONGPM-PC\\SQLEXPRESS;Initial Catalog=shoponline;Persist Security Inf" +
            "o=True;User ID=sa;Password=123")]
        public string shoponlineConnectionString1 {
            get {
                return ((string)(this["shoponlineConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=URON\\SQLEXPRESS;Initial Catalog=shoponline;Persist Security Info=True" +
            ";User ID=sa;Password=123")]
        public string shoponlineConnectionString2 {
            get {
                return ((string)(this["shoponlineConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.16.20\\SERVER2008;Initial Catalog=congnghecao;User ID=sa")]
        public string congnghecaoConnectionString {
            get {
                return ((string)(this["congnghecaoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.16.20\\SERVER2008;Initial Catalog=congdoannh;User ID=sa")]
        public string congdoannhConnectionString {
            get {
                return ((string)(this["congdoannhConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.16.20\\SERVER2008;Initial Catalog=congnghecao;User ID=sa;Passw" +
            "ord=123sa")]
        public string congnghecaoConnectionString1 {
            get {
                return ((string)(this["congnghecaoConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.166.134;Initial Catalog=khoahoccn;User ID=dev")]
        public string khoahoccnConnectionString {
            get {
                return ((string)(this["khoahoccnConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.166.134;Initial Catalog=khoahoccn;User ID=dev;Password=227edf" +
            "7c86c02a44d17eec9aa5b30cd1")]
        public string khoahoccnConnectionString1 {
            get {
                return ((string)(this["khoahoccnConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.166.134;Initial Catalog=congnghesinhhoc;User ID=dev;Password=" +
            "227edf7c86c02a44d17eec9aa5b30cd1")]
        public string congnghesinhhocConnectionString {
            get {
                return ((string)(this["congnghesinhhocConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.166.134;Initial Catalog=congnghesinhhoc2;User ID=dev;Password" +
            "=227edf7c86c02a44d17eec9aa5b30cd1")]
        public string congnghesinhhoc2ConnectionString {
            get {
                return ((string)(this["congnghesinhhoc2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.166.135;Initial Catalog=congnghesinhhoc2;User ID=dev")]
        public string congnghesinhhoc2ConnectionString1 {
            get {
                return ((string)(this["congnghesinhhoc2ConnectionString1"]));
            }
        }
    }
}
