//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=ShopOnline;Persist Security Info=True;User " +
            "ID=sa;Password=291284")]
        public string ShopOnlineConnectionString {
            get {
                return ((string)(this["ShopOnlineConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CUONGPM-PC\\SQLEXPRESS;Initial Catalog=shoponline;Persist Security Inf" +
            "o=True;User ID=sa;Password=123")]
        public string shoponlineConnectionString1 {
            get {
                return ((string)(this["shoponlineConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=URON\\SQLEXPRESS;Initial Catalog=shoponline;Persist Security Info=True" +
            ";User ID=sa;Password=123")]
        public string shoponlineConnectionString2 {
            get {
                return ((string)(this["shoponlineConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.16.20\\SERVER2008;Initial Catalog=congdoanct;Persist Security " +
            "Info=True;User ID=sa;Password=123sa")]
        public string congdoanctConnectionString {
            get {
                return ((string)(this["congdoanctConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=118.70.207.32;Initial Catalog=cdct;User ID=lcee")]
        public string cdctConnectionString {
            get {
                return ((string)(this["cdctConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=118.70.207.32;Initial Catalog=cdct;User ID=lcee;Password=lcee")]
        public string cdctConnectionString1 {
            get {
                return ((string)(this["cdctConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.166.134;Initial Catalog=beta_cdct;Integrated Security=False;U" +
            "ser ID=congdoanct;Min Pool Size=5;Max Pool Size=60;MultipleActiveResultSets=True" +
            ";Connect Timeout=600")]
        public string beta_cdctConnectionString {
            get {
                return ((string)(this["beta_cdctConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.166.134;Initial Catalog=beta_cdct;Integrated Security=False;U" +
            "ser ID=congdoanct;Password=1ef627f737cdfd1c429e72bbd90b8a8e;Min Pool Size=5;Max " +
            "Pool Size=60;MultipleActiveResultSets=True;Connect Timeout=600")]
        public string beta_cdctConnectionString1 {
            get {
                return ((string)(this["beta_cdctConnectionString1"]));
            }
        }
    }
}
