//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=ShopOnline;Persist Security Info=True;User " +
            "ID=sa;Password=291284")]
        public string ShopOnlineConnectionString {
            get {
                return ((string)(this["ShopOnlineConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CUONGPM-PC\\SQLEXPRESS;Initial Catalog=shoponline;Persist Security Inf" +
            "o=True;User ID=sa;Password=123")]
        public string shoponlineConnectionString1 {
            get {
                return ((string)(this["shoponlineConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=URON\\SQLEXPRESS;Initial Catalog=shoponline;Persist Security Info=True" +
            ";User ID=sa;Password=123")]
        public string shoponlineConnectionString2 {
            get {
                return ((string)(this["shoponlineConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.166.134;Initial Catalog=congdoanxaydung;Persist Security Info" +
            "=True;User ID=congdoanxaydung")]
        public string congdoanxaydungConnectionString {
            get {
                return ((string)(this["congdoanxaydungConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.166.134;Initial Catalog=betacdxd;Integrated Security=False;Us" +
            "er ID=congdoanxaydung;Password=eb9c19ee15541de444de7bf0ff447314;Min Pool Size=5;" +
            "Max Pool Size=60;MultipleActiveResultSets=True;Connect Timeout=600")]
        public string betacdxdConnectionString {
            get {
                return ((string)(this["betacdxdConnectionString"]));
            }
        }
    }
}
