//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=ShopOnline;Persist Security Info=True;User " +
            "ID=sa;Password=291284")]
        public string ShopOnlineConnectionString {
            get {
                return ((string)(this["ShopOnlineConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CUONGPM-PC\\SQLEXPRESS;Initial Catalog=shoponline;Persist Security Inf" +
            "o=True;User ID=sa;Password=123")]
        public string shoponlineConnectionString1 {
            get {
                return ((string)(this["shoponlineConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=URON\\SQLEXPRESS;Initial Catalog=shoponline;Persist Security Info=True" +
            ";User ID=sa;Password=123")]
        public string shoponlineConnectionString2 {
            get {
                return ((string)(this["shoponlineConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.16.20\\SERVER2008;Initial Catalog=congdoanct;Persist Security " +
            "Info=True;User ID=sa;Password=123sa")]
        public string congdoanctConnectionString {
            get {
                return ((string)(this["congdoanctConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CUONGPM\\SQLEXPRESS;Initial Catalog=congdoannh;User ID=sa")]
        public string congdoannhConnectionString {
            get {
                return ((string)(this["congdoannhConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.16.20\\SERVER2008;Initial Catalog=congdoannh;User ID=sa;Passwo" +
            "rd=123sa")]
        public string congdoannhConnectionString1 {
            get {
                return ((string)(this["congdoannhConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=118.70.207.32;Initial Catalog=cdnh;Persist Security Info=True;User ID" +
            "=tieungao.choi.vn")]
        public string cdnhConnectionString {
            get {
                return ((string)(this["cdnhConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=118.70.207.32;Initial Catalog=cdnh;Persist Security Info=True;User ID" +
            "=tieungao.choi.vn;Password=TiEuN&^899078")]
        public string cdnhConnectionString1 {
            get {
                return ((string)(this["cdnhConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.166.134;Initial Catalog=shoponline;Persist Security Info=True" +
            ";User ID=dev;Password=227edf7c86c02a44d17eec9aa5b30cd1")]
        public string shoponlineConnectionString3 {
            get {
                return ((string)(this["shoponlineConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.166.134;Initial Catalog=beptanphu;Integrated Security=False;U" +
            "ser ID=dev;Password=227edf7c86c02a44d17eec9aa5b30cd1;Min Pool Size=5;Max Pool Si" +
            "ze=60;MultipleActiveResultSets=True;Connect Timeout=600")]
        public string beptanphuConnectionString {
            get {
                return ((string)(this["beptanphuConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.166.134;Initial Catalog=altai;Integrated Security=False;User " +
            "ID=dev;Password=227edf7c86c02a44d17eec9aa5b30cd1;Min Pool Size=5;Max Pool Size=6" +
            "0;MultipleActiveResultSets=True;Connect Timeout=600")]
        public string altaiConnectionString {
            get {
                return ((string)(this["altaiConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.166.134;Initial Catalog=autojp;Integrated Security=False;User" +
            " ID=dev;Password=227edf7c86c02a44d17eec9aa5b30cd1;Min Pool Size=5;Max Pool Size=" +
            "60;MultipleActiveResultSets=True;Connect Timeout=600")]
        public string autojpConnectionString {
            get {
                return ((string)(this["autojpConnectionString"]));
            }
        }
    }
}
