//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=ShopOnline;Persist Security Info=True;User " +
            "ID=sa;Password=291284")]
        public string ShopOnlineConnectionString {
            get {
                return ((string)(this["ShopOnlineConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CUONGPM-PC\\SQLEXPRESS;Initial Catalog=shoponline;Persist Security Inf" +
            "o=True;User ID=sa;Password=123")]
        public string shoponlineConnectionString1 {
            get {
                return ((string)(this["shoponlineConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=URON\\SQLEXPRESS;Initial Catalog=shoponline;Persist Security Info=True" +
            ";User ID=sa;Password=123")]
        public string shoponlineConnectionString2 {
            get {
                return ((string)(this["shoponlineConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.16.20\\SERVER2008;Initial Catalog=congdoanct;Persist Security " +
            "Info=True;User ID=sa;Password=123sa")]
        public string congdoanctConnectionString {
            get {
                return ((string)(this["congdoanctConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.16.20\\SERVER2008;Initial Catalog=news_dev;Persist Security In" +
            "fo=True;User ID=sa")]
        public string news_devConnectionString {
            get {
                return ((string)(this["news_devConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.16.20\\SERVER2008;Initial Catalog=news_dev;User ID=sa;Password" +
            "=123sa")]
        public string news_devConnectionString1 {
            get {
                return ((string)(this["news_devConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.121.43,1433\\SQLEXPRESS;Initial Catalog=baogiaothong.vn;User I" +
            "D=sa")]
        public string baogiaothong_vnConnectionString {
            get {
                return ((string)(this["baogiaothong_vnConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.121.43,1433\\SQLEXPRESS;Initial Catalog=baogiaothong.vn;User I" +
            "D=sa;Password=giaothong@123")]
        public string baogiaothong_vnConnectionString1 {
            get {
                return ((string)(this["baogiaothong_vnConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.166.134;Initial Catalog=baogiaothong.vn;Persist Security Info" +
            "=True;User ID=baogiaothong")]
        public string baogiaothong_vnConnectionString2 {
            get {
                return ((string)(this["baogiaothong_vnConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.166.134;Initial Catalog=tietkiemnangluong;Persist Security In" +
            "fo=True;User ID=tietkiemnangluong")]
        public string tietkiemnangluongConnectionString {
            get {
                return ((string)(this["tietkiemnangluongConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.166.134;Initial Catalog=tietkiemnangluong;Persist Security In" +
            "fo=True;User ID=tietkiemnangluong;Password=tknl@2014@")]
        public string tietkiemnangluongConnectionString1 {
            get {
                return ((string)(this["tietkiemnangluongConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=203.162.166.135;Initial Catalog=tietkiemnangluong;User ID=dev;Passwor" +
            "d=227edf7c86c02a44d17eec9aa5b30cd1")]
        public string tietkiemnangluongConnectionString2 {
            get {
                return ((string)(this["tietkiemnangluongConnectionString2"]));
            }
        }
    }
}
