//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các ngân hàng tham gia.
        /// </summary>
        internal static string BankSupport {
            get {
                return ResourceManager.GetString("BankSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hiệu.
        /// </summary>
        internal static string DocCode {
            get {
                return ResourceManager.GetString("DocCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string DocDescription {
            get {
                return ResourceManager.GetString("DocDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải về.
        /// </summary>
        internal static string DocDownload {
            get {
                return ResourceManager.GetString("DocDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày có hiệu lực.
        /// </summary>
        internal static string DocEffectiveDate {
            get {
                return ResourceManager.GetString("DocEffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hiệu lực.
        /// </summary>
        internal static string DocExpiryDate {
            get {
                return ResourceManager.GetString("DocExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên văn bản.
        /// </summary>
        internal static string DocName {
            get {
                return ResourceManager.GetString("DocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài liệu.
        /// </summary>
        internal static string DocName2 {
            get {
                return ResourceManager.GetString("DocName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        internal static string DocNumber {
            get {
                return ResourceManager.GetString("DocNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày ban hành.
        /// </summary>
        internal static string DocPublishDate {
            get {
                return ResourceManager.GetString("DocPublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản khác.
        /// </summary>
        internal static string DocRelate {
            get {
                return ResourceManager.GetString("DocRelate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu khác.
        /// </summary>
        internal static string DocRelate2 {
            get {
                return ResourceManager.GetString("DocRelate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người ký.
        /// </summary>
        internal static string DocSignedBy {
            get {
                return ResourceManager.GetString("DocSignedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ quan ban hành.
        /// </summary>
        internal static string DocSignedByDesc {
            get {
                return ResourceManager.GetString("DocSignedByDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem online.
        /// </summary>
        internal static string DocViewOnline {
            get {
                return ResourceManager.GetString("DocViewOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Email.
        /// </summary>
        internal static string EmailValidateEmpty {
            get {
                return ResourceManager.GetString("EmailValidateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sai định dạng.
        /// </summary>
        internal static string EmailValidateFormat {
            get {
                return ResourceManager.GetString("EmailValidateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỏi đáp.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng để lại câu hỏi của bạn tại đây! Chúng tôi sẽ liên hệ bạn sớm nhất.
        /// </summary>
        internal static string FeedBackMessage {
            get {
                return ResourceManager.GetString("FeedBackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Bản quyền thuộc Vụ Tiết kiệm năng lượng và Phát triển bền vững, Bộ Công Thương&lt;br&gt;
        ///                    Phòng 307, Nhà B, 54 Hai Bà Trưng, quận Hoàn Kiếm, Hà Nội. &lt;br&gt;
        ///                    ĐT: 024.22202358 &lt;br&gt;
        ///					Giấy phép hoạt động số 43/GP-TTĐT do Cục Phát thanh truyền hình và Thông tin điện tử, Bộ Thông tin và Truyền thông cấp ngày 12 tháng 3 năm 2019&lt;br&gt;  
        ///                    Ghi rõ nguồn:  &lt;a href=&quot;http://www.scp.gov.vn/&quot;&gt; http://www.scp.gov.vn/&lt;/a&gt;  khi sử dụng thông tin từ website này..
        /// </summary>
        internal static string FooterContent {
            get {
                return ResourceManager.GetString("FooterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phát triển bởi.
        /// </summary>
        internal static string FooterDev {
            get {
                return ResourceManager.GetString("FooterDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số lượt truy cập.
        /// </summary>
        internal static string FooterView {
            get {
                return ResourceManager.GetString("FooterView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập họ tên.
        /// </summary>
        internal static string FullNameEmpty {
            get {
                return ResourceManager.GetString("FullNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài báo nổi bật.
        /// </summary>
        internal static string HotArticle {
            get {
                return ResourceManager.GetString("HotArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khóa.
        /// </summary>
        internal static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin mới.
        /// </summary>
        internal static string LastestNews {
            get {
                return ResourceManager.GetString("LastestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết.
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa điểm.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/images/logo.png?vs=01.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết.
        /// </summary>
        internal static string MenuLink {
            get {
                return ResourceManager.GetString("MenuLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string MenuSearch {
            get {
                return ResourceManager.GetString("MenuSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống! Vui lòng quay lại trong giây lát.
        /// </summary>
        internal static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn gửi thông tin quá nhiều lần. Vui lòng chờ giây lát.
        /// </summary>
        internal static string MessageSoMuch {
            get {
                return ResourceManager.GetString("MessageSoMuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string NewsUpdate {
            get {
                return ResourceManager.GetString("NewsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản in.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập câu hỏi.
        /// </summary>
        internal static string QuestionValidateEmpty {
            get {
                return ResourceManager.GetString("QuestionValidateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài báo khác.
        /// </summary>
        internal static string RelateArticle {
            get {
                return ResourceManager.GetString("RelateArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin liên quan.
        /// </summary>
        internal static string RelateNews {
            get {
                return ResourceManager.GetString("RelateNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi câu hỏi.
        /// </summary>
        internal static string SendQuestion {
            get {
                return ResourceManager.GetString("SendQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang thông tin điện tử Cục Công Nghiệp.
        /// </summary>
        internal static string SiteDescription {
            get {
                return ResourceManager.GetString("SiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sơ đồ website.
        /// </summary>
        internal static string SiteMap {
            get {
                return ResourceManager.GetString("SiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang thông tin điện tử Cục Công Nghiệp.
        /// </summary>
        internal static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin xem nhiều.
        /// </summary>
        internal static string TopViewNews {
            get {
                return ResourceManager.GetString("TopViewNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
    }
}
